language: ruby
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - jruby
env:
  - RAILS_VERSION=5.1
  - RAILS_VERSION=4.2
matrix:
  allow_failures:
    - rvm: jruby
before_install:
- gem update --system
- gem install bundler
before_script:
- psql -c 'create database postgresql_cursors_unit_tests;' -U postgres
