# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{activerecord-postgresql-cursors}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{J Smith}]
  s.date = %q{2011-09-28}
  s.description = %q{Provides some support for PostgreSQL cursors in ActiveRecord.}
  s.email = %q{code@zoocasa.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "activerecord-postgresql-cursors.gemspec",
    "init.rb",
    "lib/activerecord-postgresql-cursors.rb",
    "lib/postgresql_cursors_2.rb",
    "lib/postgresql_cursors_3.rb",
    "test/cursor_tests.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/zoocasa/activerecord-postgresql-cursors}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{Provides some support for PostgreSQL cursors in ActiveRecord.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
  s.add_dependency "activerecord"
  s.add_dependency "pg"
  s.add_development_dependency "test-unit"
end

